# _config.yml
title: Conferência BMP
description: Sistema Web de Controle e Conferência de Material Carga
baseurl: "/material-carga"       # Se for uma página de repositório, coloque: "/nome-do-repositorio"
url: ""

# Ignora pastas ou dependências fora do escopo do Jekyll
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock